name:                postgresql-common-persistent
version:             0.1.0.0
github:              "iand675/postgresql-common"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Persistent compatibility for postgresql-common
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/postgresql-common-persistent#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- persistent
- postgresql-common
- text

library:
  source-dirs: src

tests:
  postgresql-common-persistent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postgresql-common-persistent
